// Generated by scripts/discover-links.mjs.
// Review changes before committing them as test expectations.

export const dropdownRoutes = [
  {
    "id": "online-show-registration",
    "triggerName": "Car Show",
    "linkName": "Online Show Registration",
    "href": "register_content.html",
    "expectedUrl": "https://www.southernknightscruisers.com/register_content.html",
    "expectedHeading": "Veterans Car Show Registration"
  },
  {
    "id": "online-vendor-registration",
    "triggerName": "Car Show",
    "linkName": "Online Vendor Registration",
    "href": "vendor-register_content.html",
    "expectedUrl": "https://www.southernknightscruisers.com/vendor-register_content.html",
    "expectedHeading": "Veterans Car Show Vendor Registration"
  },
  {
    "id": "online-food-vendor-registration",
    "triggerName": "Car Show",
    "linkName": "Online Food Vendor Registration",
    "href": "food-vendor-register_content.html",
    "expectedUrl": "https://www.southernknightscruisers.com/food-vendor-register_content.html",
    "expectedHeading": "Veterans Car Show Food Vendor Registration"
  },
  {
    "id": "about-our-veterans-organizations",
    "triggerName": "Car Show",
    "linkName": "About Our Veteran's Organizations",
    "href": "vet-organizations.html",
    "expectedUrl": "https://www.southernknightscruisers.com/vet-organizations.html",
    "expectedHeading": "About The Veteran's Organizations We Support"
  }
] as const;

export type DropdownRoute =
  (typeof dropdownRoutes)[number];
