// Generated by scripts/discover-links.mjs.
// Review changes before committing them as test expectations.

export const externalLinks = [
  {
    "category": "External",
    "names": [
      "Facebook",
      "(unnamed link)"
    ],
    "href": "https://www.facebook.com/pages/Southern-Knights-Cruisers-Inc/220760671474",
    "sourcePages": [
      "https://www.southernknightscruisers.com/index.html",
      "https://www.southernknightscruisers.com/about.html",
      "https://www.southernknightscruisers.com/events.html",
      "https://www.southernknightscruisers.com/gallery.html",
      "https://www.southernknightscruisers.com/news.html",
      "https://www.southernknightscruisers.com/sponsors.html",
      "https://www.southernknightscruisers.com/veterans-show.html",
      "https://www.southernknightscruisers.com/register_content.html",
      "https://www.southernknightscruisers.com/vendor-register_content.html",
      "https://www.southernknightscruisers.com/food-vendor-register_content.html",
      "https://www.southernknightscruisers.com/vet-organizations.html",
      "https://www.southernknightscruisers.com/contact.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "External",
    "names": [
      "Hardees"
    ],
    "href": "https://www.hardees.com/",
    "sourcePages": [
      "https://www.southernknightscruisers.com/index.html",
      "https://www.southernknightscruisers.com/about.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "External",
    "names": [
      "Strosnider Chevrolet"
    ],
    "href": "https://www.strosniderchevrolet.com/",
    "sourcePages": [
      "https://www.southernknightscruisers.com/index.html",
      "https://www.southernknightscruisers.com/about.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "External",
    "names": [
      "Virginia Motorsport Park"
    ],
    "href": "https://www.vmpdrag.com/",
    "sourcePages": [
      "https://www.southernknightscruisers.com/index.html",
      "https://www.southernknightscruisers.com/about.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "External",
    "names": [
      "Paradise Road Speed & Custom",
      "Paradise Road Speed and Custom"
    ],
    "href": "https://www.facebook.com/paradise.road.777/",
    "sourcePages": [
      "https://www.southernknightscruisers.com/index.html",
      "https://www.southernknightscruisers.com/about.html",
      "https://www.southernknightscruisers.com/events.html",
      "https://www.southernknightscruisers.com/gallery.html",
      "https://www.southernknightscruisers.com/news.html",
      "https://www.southernknightscruisers.com/sponsors.html",
      "https://www.southernknightscruisers.com/veterans-show.html",
      "https://www.southernknightscruisers.com/register_content.html",
      "https://www.southernknightscruisers.com/vendor-register_content.html",
      "https://www.southernknightscruisers.com/food-vendor-register_content.html",
      "https://www.southernknightscruisers.com/vet-organizations.html",
      "https://www.southernknightscruisers.com/contact.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "External",
    "names": [
      "Masi's Musclecar Garage"
    ],
    "href": "https://masismusclecargarage.com/",
    "sourcePages": [
      "https://www.southernknightscruisers.com/index.html",
      "https://www.southernknightscruisers.com/about.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "External",
    "names": [
      "Leete Tire Complete Auto",
      "Leete Tire Complete Auto Service"
    ],
    "href": "https://www.leetetire.com/",
    "sourcePages": [
      "https://www.southernknightscruisers.com/index.html",
      "https://www.southernknightscruisers.com/about.html",
      "https://www.southernknightscruisers.com/events.html",
      "https://www.southernknightscruisers.com/gallery.html",
      "https://www.southernknightscruisers.com/news.html",
      "https://www.southernknightscruisers.com/sponsors.html",
      "https://www.southernknightscruisers.com/veterans-show.html",
      "https://www.southernknightscruisers.com/register_content.html",
      "https://www.southernknightscruisers.com/vendor-register_content.html",
      "https://www.southernknightscruisers.com/food-vendor-register_content.html",
      "https://www.southernknightscruisers.com/vet-organizations.html",
      "https://www.southernknightscruisers.com/contact.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "External",
    "names": [
      "Mikes Outdoor Supply"
    ],
    "href": "https://mikesld.com/",
    "sourcePages": [
      "https://www.southernknightscruisers.com/index.html",
      "https://www.southernknightscruisers.com/about.html",
      "https://www.southernknightscruisers.com/events.html",
      "https://www.southernknightscruisers.com/gallery.html",
      "https://www.southernknightscruisers.com/news.html",
      "https://www.southernknightscruisers.com/sponsors.html",
      "https://www.southernknightscruisers.com/veterans-show.html",
      "https://www.southernknightscruisers.com/register_content.html",
      "https://www.southernknightscruisers.com/vendor-register_content.html",
      "https://www.southernknightscruisers.com/food-vendor-register_content.html",
      "https://www.southernknightscruisers.com/vet-organizations.html",
      "https://www.southernknightscruisers.com/contact.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "External",
    "names": [
      "Mikes on facebook"
    ],
    "href": "https://www.facebook.com/Vapaverdealer",
    "sourcePages": [
      "https://www.southernknightscruisers.com/index.html",
      "https://www.southernknightscruisers.com/about.html",
      "https://www.southernknightscruisers.com/events.html",
      "https://www.southernknightscruisers.com/gallery.html",
      "https://www.southernknightscruisers.com/news.html",
      "https://www.southernknightscruisers.com/sponsors.html",
      "https://www.southernknightscruisers.com/veterans-show.html",
      "https://www.southernknightscruisers.com/register_content.html",
      "https://www.southernknightscruisers.com/vendor-register_content.html",
      "https://www.southernknightscruisers.com/food-vendor-register_content.html",
      "https://www.southernknightscruisers.com/vet-organizations.html",
      "https://www.southernknightscruisers.com/contact.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "External",
    "names": [
      "Custom Autosound"
    ],
    "href": "https://www.customautosoundmfg.com/",
    "sourcePages": [
      "https://www.southernknightscruisers.com/index.html",
      "https://www.southernknightscruisers.com/about.html",
      "https://www.southernknightscruisers.com/events.html",
      "https://www.southernknightscruisers.com/gallery.html",
      "https://www.southernknightscruisers.com/news.html",
      "https://www.southernknightscruisers.com/sponsors.html",
      "https://www.southernknightscruisers.com/veterans-show.html",
      "https://www.southernknightscruisers.com/register_content.html",
      "https://www.southernknightscruisers.com/vendor-register_content.html",
      "https://www.southernknightscruisers.com/food-vendor-register_content.html",
      "https://www.southernknightscruisers.com/vet-organizations.html",
      "https://www.southernknightscruisers.com/contact.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "External",
    "names": [
      "CA on facebook",
      "Custom Autosound on facebook"
    ],
    "href": "https://www.facebook.com/CustomAutosoundMFG/",
    "sourcePages": [
      "https://www.southernknightscruisers.com/index.html",
      "https://www.southernknightscruisers.com/about.html",
      "https://www.southernknightscruisers.com/events.html",
      "https://www.southernknightscruisers.com/gallery.html",
      "https://www.southernknightscruisers.com/news.html",
      "https://www.southernknightscruisers.com/sponsors.html",
      "https://www.southernknightscruisers.com/veterans-show.html",
      "https://www.southernknightscruisers.com/register_content.html",
      "https://www.southernknightscruisers.com/vendor-register_content.html",
      "https://www.southernknightscruisers.com/food-vendor-register_content.html",
      "https://www.southernknightscruisers.com/vet-organizations.html",
      "https://www.southernknightscruisers.com/contact.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "External",
    "names": [
      "Viking Bags"
    ],
    "href": "https://www.vikingbags.com/collections/motorcycle-backpacks",
    "sourcePages": [
      "https://www.southernknightscruisers.com/index.html",
      "https://www.southernknightscruisers.com/about.html",
      "https://www.southernknightscruisers.com/events.html",
      "https://www.southernknightscruisers.com/gallery.html",
      "https://www.southernknightscruisers.com/news.html",
      "https://www.southernknightscruisers.com/sponsors.html",
      "https://www.southernknightscruisers.com/veterans-show.html",
      "https://www.southernknightscruisers.com/register_content.html",
      "https://www.southernknightscruisers.com/vendor-register_content.html",
      "https://www.southernknightscruisers.com/food-vendor-register_content.html",
      "https://www.southernknightscruisers.com/vet-organizations.html",
      "https://www.southernknightscruisers.com/contact.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "External",
    "names": [
      "Elite Contracting Group"
    ],
    "href": "https://elitecontractinggroup.com/",
    "sourcePages": [
      "https://www.southernknightscruisers.com/index.html",
      "https://www.southernknightscruisers.com/about.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "External",
    "names": [
      "Mecum Auctions",
      "Viking Bags"
    ],
    "href": "https://www.mecum.com/",
    "sourcePages": [
      "https://www.southernknightscruisers.com/index.html",
      "https://www.southernknightscruisers.com/about.html",
      "https://www.southernknightscruisers.com/events.html",
      "https://www.southernknightscruisers.com/gallery.html",
      "https://www.southernknightscruisers.com/news.html",
      "https://www.southernknightscruisers.com/sponsors.html",
      "https://www.southernknightscruisers.com/veterans-show.html",
      "https://www.southernknightscruisers.com/register_content.html",
      "https://www.southernknightscruisers.com/vendor-register_content.html",
      "https://www.southernknightscruisers.com/food-vendor-register_content.html",
      "https://www.southernknightscruisers.com/vet-organizations.html",
      "https://www.southernknightscruisers.com/contact.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "External",
    "names": [
      "DriveLogs"
    ],
    "href": "https://www.drivelogsusa.com/",
    "sourcePages": [
      "https://www.southernknightscruisers.com/index.html",
      "https://www.southernknightscruisers.com/about.html",
      "https://www.southernknightscruisers.com/events.html",
      "https://www.southernknightscruisers.com/gallery.html",
      "https://www.southernknightscruisers.com/news.html",
      "https://www.southernknightscruisers.com/sponsors.html",
      "https://www.southernknightscruisers.com/veterans-show.html",
      "https://www.southernknightscruisers.com/register_content.html",
      "https://www.southernknightscruisers.com/vendor-register_content.html",
      "https://www.southernknightscruisers.com/food-vendor-register_content.html",
      "https://www.southernknightscruisers.com/vet-organizations.html",
      "https://www.southernknightscruisers.com/contact.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "External",
    "names": [
      "Colonial Plumbing"
    ],
    "href": "https://colonialplumbing.com/",
    "sourcePages": [
      "https://www.southernknightscruisers.com/index.html",
      "https://www.southernknightscruisers.com/about.html",
      "https://www.southernknightscruisers.com/events.html",
      "https://www.southernknightscruisers.com/gallery.html",
      "https://www.southernknightscruisers.com/news.html",
      "https://www.southernknightscruisers.com/sponsors.html",
      "https://www.southernknightscruisers.com/veterans-show.html",
      "https://www.southernknightscruisers.com/register_content.html",
      "https://www.southernknightscruisers.com/vendor-register_content.html",
      "https://www.southernknightscruisers.com/food-vendor-register_content.html",
      "https://www.southernknightscruisers.com/vet-organizations.html",
      "https://www.southernknightscruisers.com/contact.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "External",
    "names": [
      "First Bank"
    ],
    "href": "https://www.fbvirginia.com/",
    "sourcePages": [
      "https://www.southernknightscruisers.com/index.html",
      "https://www.southernknightscruisers.com/about.html",
      "https://www.southernknightscruisers.com/events.html",
      "https://www.southernknightscruisers.com/gallery.html",
      "https://www.southernknightscruisers.com/news.html",
      "https://www.southernknightscruisers.com/sponsors.html",
      "https://www.southernknightscruisers.com/veterans-show.html",
      "https://www.southernknightscruisers.com/register_content.html",
      "https://www.southernknightscruisers.com/vendor-register_content.html",
      "https://www.southernknightscruisers.com/food-vendor-register_content.html",
      "https://www.southernknightscruisers.com/vet-organizations.html",
      "https://www.southernknightscruisers.com/contact.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "External",
    "names": [
      "Fort Lee’s Holiday Helper Association",
      "Fort Lee's Holiday Helper Association"
    ],
    "href": "http://www.holidayhelperassociation.com/",
    "sourcePages": [
      "https://www.southernknightscruisers.com/about.html",
      "https://www.southernknightscruisers.com/events.html",
      "https://www.southernknightscruisers.com/gallery.html",
      "https://www.southernknightscruisers.com/news.html",
      "https://www.southernknightscruisers.com/sponsors.html",
      "https://www.southernknightscruisers.com/veterans-show.html",
      "https://www.southernknightscruisers.com/contact.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "External",
    "names": [
      "The Fisher House",
      "Richmond Fisher House and Foundation"
    ],
    "href": "http://richmondfisherhouse.org/",
    "sourcePages": [
      "https://www.southernknightscruisers.com/about.html",
      "https://www.southernknightscruisers.com/events.html",
      "https://www.southernknightscruisers.com/gallery.html",
      "https://www.southernknightscruisers.com/news.html",
      "https://www.southernknightscruisers.com/sponsors.html",
      "https://www.southernknightscruisers.com/veterans-show.html",
      "https://www.southernknightscruisers.com/contact.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "External",
    "names": [
      "McGuire Veterans Hospital",
      "Richmond VA Medical Center Fund #1161, formally Hunter Holmes McGuire Medical Center"
    ],
    "href": "http://www.richmond.va.gov/",
    "sourcePages": [
      "https://www.southernknightscruisers.com/about.html",
      "https://www.southernknightscruisers.com/events.html",
      "https://www.southernknightscruisers.com/gallery.html",
      "https://www.southernknightscruisers.com/news.html",
      "https://www.southernknightscruisers.com/sponsors.html",
      "https://www.southernknightscruisers.com/veterans-show.html",
      "https://www.southernknightscruisers.com/contact.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "External",
    "names": [
      "American Legion Post 284, Colonial Heights, Virginia"
    ],
    "href": "http://alpost284.x10host.com/",
    "sourcePages": [
      "https://www.southernknightscruisers.com/about.html",
      "https://www.southernknightscruisers.com/events.html",
      "https://www.southernknightscruisers.com/gallery.html",
      "https://www.southernknightscruisers.com/news.html",
      "https://www.southernknightscruisers.com/sponsors.html",
      "https://www.southernknightscruisers.com/veterans-show.html",
      "https://www.southernknightscruisers.com/contact.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "External",
    "names": [
      "www.rbc.edu"
    ],
    "href": "http://www.rbc.edu/",
    "sourcePages": [
      "https://www.southernknightscruisers.com/about.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "External",
    "names": [
      "Find more shows and events."
    ],
    "href": "http://carclubcouncil.com/cal.html",
    "sourcePages": [
      "https://www.southernknightscruisers.com/events.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "External",
    "names": [
      "Hardees",
      "Hardee's"
    ],
    "href": "http://www.hardees.com/",
    "sourcePages": [
      "https://www.southernknightscruisers.com/events.html",
      "https://www.southernknightscruisers.com/gallery.html",
      "https://www.southernknightscruisers.com/news.html",
      "https://www.southernknightscruisers.com/sponsors.html",
      "https://www.southernknightscruisers.com/veterans-show.html",
      "https://www.southernknightscruisers.com/register_content.html",
      "https://www.southernknightscruisers.com/vendor-register_content.html",
      "https://www.southernknightscruisers.com/food-vendor-register_content.html",
      "https://www.southernknightscruisers.com/vet-organizations.html",
      "https://www.southernknightscruisers.com/contact.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "External",
    "names": [
      "Strosnider Chevrolet"
    ],
    "href": "http://www.strosniderchevrolet.com/",
    "sourcePages": [
      "https://www.southernknightscruisers.com/events.html",
      "https://www.southernknightscruisers.com/gallery.html",
      "https://www.southernknightscruisers.com/news.html",
      "https://www.southernknightscruisers.com/sponsors.html",
      "https://www.southernknightscruisers.com/veterans-show.html",
      "https://www.southernknightscruisers.com/register_content.html",
      "https://www.southernknightscruisers.com/vendor-register_content.html",
      "https://www.southernknightscruisers.com/food-vendor-register_content.html",
      "https://www.southernknightscruisers.com/vet-organizations.html",
      "https://www.southernknightscruisers.com/contact.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "External",
    "names": [
      "Virginia Motorsport Park",
      "Virginia Motorsports Park",
      "Virgnia Motorsports Park"
    ],
    "href": "http://www.vmpdrag.com/",
    "sourcePages": [
      "https://www.southernknightscruisers.com/events.html",
      "https://www.southernknightscruisers.com/gallery.html",
      "https://www.southernknightscruisers.com/news.html",
      "https://www.southernknightscruisers.com/sponsors.html",
      "https://www.southernknightscruisers.com/veterans-show.html",
      "https://www.southernknightscruisers.com/register_content.html",
      "https://www.southernknightscruisers.com/vendor-register_content.html",
      "https://www.southernknightscruisers.com/food-vendor-register_content.html",
      "https://www.southernknightscruisers.com/vet-organizations.html",
      "https://www.southernknightscruisers.com/contact.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "External",
    "names": [
      "Masi's Musclecar Garage"
    ],
    "href": "http://masismusclecargarage.com/",
    "sourcePages": [
      "https://www.southernknightscruisers.com/events.html",
      "https://www.southernknightscruisers.com/gallery.html",
      "https://www.southernknightscruisers.com/news.html",
      "https://www.southernknightscruisers.com/sponsors.html",
      "https://www.southernknightscruisers.com/veterans-show.html",
      "https://www.southernknightscruisers.com/register_content.html",
      "https://www.southernknightscruisers.com/vendor-register_content.html",
      "https://www.southernknightscruisers.com/food-vendor-register_content.html",
      "https://www.southernknightscruisers.com/vet-organizations.html",
      "https://www.southernknightscruisers.com/contact.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "External",
    "names": [
      "Elite Contracting Group",
      "(unnamed link)",
      "Elite Contracting"
    ],
    "href": "http://elitecontractinggroup.com/",
    "sourcePages": [
      "https://www.southernknightscruisers.com/events.html",
      "https://www.southernknightscruisers.com/gallery.html",
      "https://www.southernknightscruisers.com/news.html",
      "https://www.southernknightscruisers.com/sponsors.html",
      "https://www.southernknightscruisers.com/veterans-show.html",
      "https://www.southernknightscruisers.com/register_content.html",
      "https://www.southernknightscruisers.com/vendor-register_content.html",
      "https://www.southernknightscruisers.com/food-vendor-register_content.html",
      "https://www.southernknightscruisers.com/vet-organizations.html",
      "https://www.southernknightscruisers.com/contact.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "External",
    "names": [
      "Chesdin Automotive and Collision"
    ],
    "href": "http://www.chesdinauto.com/",
    "sourcePages": [
      "https://www.southernknightscruisers.com/sponsors.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "External",
    "names": [
      "Ray's Upholstery & Auto Restoration"
    ],
    "href": "http://vaupholstery.com/",
    "sourcePages": [
      "https://www.southernknightscruisers.com/sponsors.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "External",
    "names": [
      "Bojangles'"
    ],
    "href": "https://www.becajun.com/",
    "sourcePages": [
      "https://www.southernknightscruisers.com/sponsors.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "External",
    "names": [
      "Designed Air Services"
    ],
    "href": "https://www.facebook.com/DesignedAirServices",
    "sourcePages": [
      "https://www.southernknightscruisers.com/sponsors.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "External",
    "names": [
      "Paradise Road Speed & Custom"
    ],
    "href": "http://paradiseroadspeedandcustom.1freecart.com/",
    "sourcePages": [
      "https://www.southernknightscruisers.com/sponsors.html"
    ],
    "elementTypes": [
      "link"
    ]
  }
] as const;

export type ExternalLink =
  (typeof externalLinks)[number];
