// Generated by scripts/discovery/homepage-navigation.mjs.
// Review this discovery data before using it as a test expectation.

export const homepageUrl = "https://the-internet.herokuapp.com/";

export const homepageNavigation = [
  {
    "number": 1,
    "name": "Fork me on GitHub",
    "rawHref": "https://github.com/tourdedave/the-internet",
    "expectedUrl": "https://github.com/tourdedave/the-internet",
    "path": "/tourdedave/the-internet",
    "isInternal": false,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "external",
    "destination": {
      "discoveryStatus": "skipped",
      "reason": "External destinations are not visited.",
      "error": null,
      "httpStatus": null,
      "finalUrl": null,
      "title": null,
      "headings": []
    }
  },
  {
    "number": 2,
    "name": "A/B Testing",
    "rawHref": "/abtest",
    "expectedUrl": "https://the-internet.herokuapp.com/abtest",
    "path": "/abtest",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "standard",
    "destination": {
      "discoveryStatus": "visited",
      "reason": null,
      "error": null,
      "httpStatus": 200,
      "finalUrl": "https://the-internet.herokuapp.com/abtest",
      "title": "The Internet",
      "headings": [
        {
          "level": "h3",
          "text": "A/B Test Variation 1",
          "isVisible": true
        }
      ]
    }
  },
  {
    "number": 3,
    "name": "Add/Remove Elements",
    "rawHref": "/add_remove_elements/",
    "expectedUrl": "https://the-internet.herokuapp.com/add_remove_elements/",
    "path": "/add_remove_elements/",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "standard",
    "destination": {
      "discoveryStatus": "visited",
      "reason": null,
      "error": null,
      "httpStatus": 200,
      "finalUrl": "https://the-internet.herokuapp.com/add_remove_elements/",
      "title": "The Internet",
      "headings": [
        {
          "level": "h3",
          "text": "Add/Remove Elements",
          "isVisible": true
        }
      ]
    }
  },
  {
    "number": 4,
    "name": "Basic Auth",
    "rawHref": "/basic_auth",
    "expectedUrl": "https://the-internet.herokuapp.com/basic_auth",
    "path": "/basic_auth",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "basic-auth",
    "destination": {
      "discoveryStatus": "skipped",
      "reason": "Requires browser authentication.",
      "error": null,
      "httpStatus": null,
      "finalUrl": null,
      "title": null,
      "headings": []
    }
  },
  {
    "number": 5,
    "name": "Broken Images",
    "rawHref": "/broken_images",
    "expectedUrl": "https://the-internet.herokuapp.com/broken_images",
    "path": "/broken_images",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "standard",
    "destination": {
      "discoveryStatus": "visited",
      "reason": null,
      "error": null,
      "httpStatus": 200,
      "finalUrl": "https://the-internet.herokuapp.com/broken_images",
      "title": "The Internet",
      "headings": [
        {
          "level": "h3",
          "text": "Broken Images",
          "isVisible": true
        }
      ]
    }
  },
  {
    "number": 6,
    "name": "Challenging DOM",
    "rawHref": "/challenging_dom",
    "expectedUrl": "https://the-internet.herokuapp.com/challenging_dom",
    "path": "/challenging_dom",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "standard",
    "destination": {
      "discoveryStatus": "visited",
      "reason": null,
      "error": null,
      "httpStatus": 200,
      "finalUrl": "https://the-internet.herokuapp.com/challenging_dom",
      "title": "The Internet",
      "headings": [
        {
          "level": "h3",
          "text": "Challenging DOM",
          "isVisible": true
        }
      ]
    }
  },
  {
    "number": 7,
    "name": "Checkboxes",
    "rawHref": "/checkboxes",
    "expectedUrl": "https://the-internet.herokuapp.com/checkboxes",
    "path": "/checkboxes",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "standard",
    "destination": {
      "discoveryStatus": "visited",
      "reason": null,
      "error": null,
      "httpStatus": 200,
      "finalUrl": "https://the-internet.herokuapp.com/checkboxes",
      "title": "The Internet",
      "headings": [
        {
          "level": "h3",
          "text": "Checkboxes",
          "isVisible": true
        }
      ]
    }
  },
  {
    "number": 8,
    "name": "Context Menu",
    "rawHref": "/context_menu",
    "expectedUrl": "https://the-internet.herokuapp.com/context_menu",
    "path": "/context_menu",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "standard",
    "destination": {
      "discoveryStatus": "visited",
      "reason": null,
      "error": null,
      "httpStatus": 200,
      "finalUrl": "https://the-internet.herokuapp.com/context_menu",
      "title": "The Internet",
      "headings": [
        {
          "level": "h3",
          "text": "Context Menu",
          "isVisible": true
        }
      ]
    }
  },
  {
    "number": 9,
    "name": "Digest Authentication",
    "rawHref": "/digest_auth",
    "expectedUrl": "https://the-internet.herokuapp.com/digest_auth",
    "path": "/digest_auth",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "digest-auth",
    "destination": {
      "discoveryStatus": "skipped",
      "reason": "Requires digest authentication.",
      "error": null,
      "httpStatus": null,
      "finalUrl": null,
      "title": null,
      "headings": []
    }
  },
  {
    "number": 10,
    "name": "Disappearing Elements",
    "rawHref": "/disappearing_elements",
    "expectedUrl": "https://the-internet.herokuapp.com/disappearing_elements",
    "path": "/disappearing_elements",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "standard",
    "destination": {
      "discoveryStatus": "visited",
      "reason": null,
      "error": null,
      "httpStatus": 200,
      "finalUrl": "https://the-internet.herokuapp.com/disappearing_elements",
      "title": "The Internet",
      "headings": [
        {
          "level": "h3",
          "text": "Disappearing Elements",
          "isVisible": true
        }
      ]
    }
  },
  {
    "number": 11,
    "name": "Drag and Drop",
    "rawHref": "/drag_and_drop",
    "expectedUrl": "https://the-internet.herokuapp.com/drag_and_drop",
    "path": "/drag_and_drop",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "standard",
    "destination": {
      "discoveryStatus": "visited",
      "reason": null,
      "error": null,
      "httpStatus": 200,
      "finalUrl": "https://the-internet.herokuapp.com/drag_and_drop",
      "title": "The Internet",
      "headings": [
        {
          "level": "h3",
          "text": "Drag and Drop",
          "isVisible": true
        }
      ]
    }
  },
  {
    "number": 12,
    "name": "Dropdown",
    "rawHref": "/dropdown",
    "expectedUrl": "https://the-internet.herokuapp.com/dropdown",
    "path": "/dropdown",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "standard",
    "destination": {
      "discoveryStatus": "visited",
      "reason": null,
      "error": null,
      "httpStatus": 200,
      "finalUrl": "https://the-internet.herokuapp.com/dropdown",
      "title": "The Internet",
      "headings": [
        {
          "level": "h3",
          "text": "Dropdown List",
          "isVisible": true
        }
      ]
    }
  },
  {
    "number": 13,
    "name": "Dynamic Content",
    "rawHref": "/dynamic_content",
    "expectedUrl": "https://the-internet.herokuapp.com/dynamic_content",
    "path": "/dynamic_content",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "standard",
    "destination": {
      "discoveryStatus": "visited",
      "reason": null,
      "error": null,
      "httpStatus": 200,
      "finalUrl": "https://the-internet.herokuapp.com/dynamic_content",
      "title": "The Internet",
      "headings": [
        {
          "level": "h3",
          "text": "Dynamic Content",
          "isVisible": true
        }
      ]
    }
  },
  {
    "number": 14,
    "name": "Dynamic Controls",
    "rawHref": "/dynamic_controls",
    "expectedUrl": "https://the-internet.herokuapp.com/dynamic_controls",
    "path": "/dynamic_controls",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "standard",
    "destination": {
      "discoveryStatus": "visited",
      "reason": null,
      "error": null,
      "httpStatus": 200,
      "finalUrl": "https://the-internet.herokuapp.com/dynamic_controls",
      "title": "The Internet",
      "headings": [
        {
          "level": "h4",
          "text": "Dynamic Controls",
          "isVisible": true
        },
        {
          "level": "h4",
          "text": "Remove/add",
          "isVisible": true
        },
        {
          "level": "h4",
          "text": "Enable/disable",
          "isVisible": true
        }
      ]
    }
  },
  {
    "number": 15,
    "name": "Dynamic Loading",
    "rawHref": "/dynamic_loading",
    "expectedUrl": "https://the-internet.herokuapp.com/dynamic_loading",
    "path": "/dynamic_loading",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "standard",
    "destination": {
      "discoveryStatus": "visited",
      "reason": null,
      "error": null,
      "httpStatus": 200,
      "finalUrl": "https://the-internet.herokuapp.com/dynamic_loading",
      "title": "The Internet",
      "headings": [
        {
          "level": "h3",
          "text": "Dynamically Loaded Page Elements",
          "isVisible": true
        }
      ]
    }
  },
  {
    "number": 16,
    "name": "Entry Ad",
    "rawHref": "/entry_ad",
    "expectedUrl": "https://the-internet.herokuapp.com/entry_ad",
    "path": "/entry_ad",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "standard",
    "destination": {
      "discoveryStatus": "visited",
      "reason": null,
      "error": null,
      "httpStatus": 200,
      "finalUrl": "https://the-internet.herokuapp.com/entry_ad",
      "title": "The Internet",
      "headings": [
        {
          "level": "h3",
          "text": "Entry Ad",
          "isVisible": true
        },
        {
          "level": "h3",
          "text": "This is a modal window",
          "isVisible": false
        }
      ]
    }
  },
  {
    "number": 17,
    "name": "Exit Intent",
    "rawHref": "/exit_intent",
    "expectedUrl": "https://the-internet.herokuapp.com/exit_intent",
    "path": "/exit_intent",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "standard",
    "destination": {
      "discoveryStatus": "visited",
      "reason": null,
      "error": null,
      "httpStatus": 200,
      "finalUrl": "https://the-internet.herokuapp.com/exit_intent",
      "title": "The Internet",
      "headings": [
        {
          "level": "h3",
          "text": "Exit Intent",
          "isVisible": true
        },
        {
          "level": "h3",
          "text": "This is a modal window",
          "isVisible": false
        }
      ]
    }
  },
  {
    "number": 18,
    "name": "File Download",
    "rawHref": "/download",
    "expectedUrl": "https://the-internet.herokuapp.com/download",
    "path": "/download",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "standard",
    "destination": {
      "discoveryStatus": "visited",
      "reason": null,
      "error": null,
      "httpStatus": 200,
      "finalUrl": "https://the-internet.herokuapp.com/download",
      "title": "The Internet",
      "headings": [
        {
          "level": "h3",
          "text": "File Downloader",
          "isVisible": true
        }
      ]
    }
  },
  {
    "number": 19,
    "name": "File Upload",
    "rawHref": "/upload",
    "expectedUrl": "https://the-internet.herokuapp.com/upload",
    "path": "/upload",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "standard",
    "destination": {
      "discoveryStatus": "visited",
      "reason": null,
      "error": null,
      "httpStatus": 200,
      "finalUrl": "https://the-internet.herokuapp.com/upload",
      "title": "The Internet",
      "headings": [
        {
          "level": "h3",
          "text": "File Uploader",
          "isVisible": true
        }
      ]
    }
  },
  {
    "number": 20,
    "name": "Floating Menu",
    "rawHref": "/floating_menu",
    "expectedUrl": "https://the-internet.herokuapp.com/floating_menu",
    "path": "/floating_menu",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "standard",
    "destination": {
      "discoveryStatus": "visited",
      "reason": null,
      "error": null,
      "httpStatus": 200,
      "finalUrl": "https://the-internet.herokuapp.com/floating_menu",
      "title": "The Internet",
      "headings": [
        {
          "level": "h3",
          "text": "Floating Menu",
          "isVisible": true
        }
      ]
    }
  },
  {
    "number": 21,
    "name": "Forgot Password",
    "rawHref": "/forgot_password",
    "expectedUrl": "https://the-internet.herokuapp.com/forgot_password",
    "path": "/forgot_password",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "standard",
    "destination": {
      "discoveryStatus": "visited",
      "reason": null,
      "error": null,
      "httpStatus": 200,
      "finalUrl": "https://the-internet.herokuapp.com/forgot_password",
      "title": "The Internet",
      "headings": [
        {
          "level": "h2",
          "text": "Forgot Password",
          "isVisible": true
        }
      ]
    }
  },
  {
    "number": 22,
    "name": "Form Authentication",
    "rawHref": "/login",
    "expectedUrl": "https://the-internet.herokuapp.com/login",
    "path": "/login",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "standard",
    "destination": {
      "discoveryStatus": "visited",
      "reason": null,
      "error": null,
      "httpStatus": 200,
      "finalUrl": "https://the-internet.herokuapp.com/login",
      "title": "The Internet",
      "headings": [
        {
          "level": "h2",
          "text": "Login Page",
          "isVisible": true
        },
        {
          "level": "h4",
          "text": "This is where you can log into the secure area. Enter tomsmith for the username and SuperSecretPassword! for the password. If the information is wrong you should see error messages.",
          "isVisible": true
        }
      ]
    }
  },
  {
    "number": 23,
    "name": "Frames",
    "rawHref": "/frames",
    "expectedUrl": "https://the-internet.herokuapp.com/frames",
    "path": "/frames",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "standard",
    "destination": {
      "discoveryStatus": "visited",
      "reason": null,
      "error": null,
      "httpStatus": 200,
      "finalUrl": "https://the-internet.herokuapp.com/frames",
      "title": "The Internet",
      "headings": [
        {
          "level": "h3",
          "text": "Frames",
          "isVisible": true
        }
      ]
    }
  },
  {
    "number": 24,
    "name": "Geolocation",
    "rawHref": "/geolocation",
    "expectedUrl": "https://the-internet.herokuapp.com/geolocation",
    "path": "/geolocation",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "standard",
    "destination": {
      "discoveryStatus": "visited",
      "reason": null,
      "error": null,
      "httpStatus": 200,
      "finalUrl": "https://the-internet.herokuapp.com/geolocation",
      "title": "The Internet",
      "headings": [
        {
          "level": "h3",
          "text": "Geolocation",
          "isVisible": true
        }
      ]
    }
  },
  {
    "number": 25,
    "name": "Horizontal Slider",
    "rawHref": "/horizontal_slider",
    "expectedUrl": "https://the-internet.herokuapp.com/horizontal_slider",
    "path": "/horizontal_slider",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "standard",
    "destination": {
      "discoveryStatus": "visited",
      "reason": null,
      "error": null,
      "httpStatus": 200,
      "finalUrl": "https://the-internet.herokuapp.com/horizontal_slider",
      "title": "The Internet",
      "headings": [
        {
          "level": "h3",
          "text": "Horizontal Slider",
          "isVisible": true
        },
        {
          "level": "h4",
          "text": "Set the focus on the slider (by clicking on it) and use the arrow keys to move it right and left. Or click and drag the slider with your mouse. It will indicate the value of the slider to the right.",
          "isVisible": true
        }
      ]
    }
  },
  {
    "number": 26,
    "name": "Hovers",
    "rawHref": "/hovers",
    "expectedUrl": "https://the-internet.herokuapp.com/hovers",
    "path": "/hovers",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "standard",
    "destination": {
      "discoveryStatus": "visited",
      "reason": null,
      "error": null,
      "httpStatus": 200,
      "finalUrl": "https://the-internet.herokuapp.com/hovers",
      "title": "The Internet",
      "headings": [
        {
          "level": "h3",
          "text": "Hovers",
          "isVisible": true
        },
        {
          "level": "h5",
          "text": "name: user1",
          "isVisible": false
        },
        {
          "level": "h5",
          "text": "name: user2",
          "isVisible": false
        },
        {
          "level": "h5",
          "text": "name: user3",
          "isVisible": false
        }
      ]
    }
  },
  {
    "number": 27,
    "name": "Infinite Scroll",
    "rawHref": "/infinite_scroll",
    "expectedUrl": "https://the-internet.herokuapp.com/infinite_scroll",
    "path": "/infinite_scroll",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "standard",
    "destination": {
      "discoveryStatus": "visited",
      "reason": null,
      "error": null,
      "httpStatus": 200,
      "finalUrl": "https://the-internet.herokuapp.com/infinite_scroll",
      "title": "The Internet",
      "headings": [
        {
          "level": "h3",
          "text": "Infinite Scroll",
          "isVisible": true
        }
      ]
    }
  },
  {
    "number": 28,
    "name": "Inputs",
    "rawHref": "/inputs",
    "expectedUrl": "https://the-internet.herokuapp.com/inputs",
    "path": "/inputs",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "standard",
    "destination": {
      "discoveryStatus": "visited",
      "reason": null,
      "error": null,
      "httpStatus": 200,
      "finalUrl": "https://the-internet.herokuapp.com/inputs",
      "title": "The Internet",
      "headings": [
        {
          "level": "h3",
          "text": "Inputs",
          "isVisible": true
        }
      ]
    }
  },
  {
    "number": 29,
    "name": "JQuery UI Menus",
    "rawHref": "/jqueryui/menu",
    "expectedUrl": "https://the-internet.herokuapp.com/jqueryui/menu",
    "path": "/jqueryui/menu",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "standard",
    "destination": {
      "discoveryStatus": "visited",
      "reason": null,
      "error": null,
      "httpStatus": 200,
      "finalUrl": "https://the-internet.herokuapp.com/jqueryui/menu",
      "title": "The Internet",
      "headings": [
        {
          "level": "h3",
          "text": "JQueryUI - Menu",
          "isVisible": true
        }
      ]
    }
  },
  {
    "number": 30,
    "name": "JavaScript Alerts",
    "rawHref": "/javascript_alerts",
    "expectedUrl": "https://the-internet.herokuapp.com/javascript_alerts",
    "path": "/javascript_alerts",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "standard",
    "destination": {
      "discoveryStatus": "visited",
      "reason": null,
      "error": null,
      "httpStatus": 200,
      "finalUrl": "https://the-internet.herokuapp.com/javascript_alerts",
      "title": "The Internet",
      "headings": [
        {
          "level": "h3",
          "text": "JavaScript Alerts",
          "isVisible": true
        },
        {
          "level": "h4",
          "text": "Result:",
          "isVisible": true
        }
      ]
    }
  },
  {
    "number": 31,
    "name": "JavaScript onload event error",
    "rawHref": "/javascript_error",
    "expectedUrl": "https://the-internet.herokuapp.com/javascript_error",
    "path": "/javascript_error",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "javascript-error",
    "destination": {
      "discoveryStatus": "visited",
      "reason": null,
      "error": null,
      "httpStatus": 200,
      "finalUrl": "https://the-internet.herokuapp.com/javascript_error",
      "title": "Page with JavaScript errors on load",
      "headings": []
    }
  },
  {
    "number": 32,
    "name": "Key Presses",
    "rawHref": "/key_presses",
    "expectedUrl": "https://the-internet.herokuapp.com/key_presses",
    "path": "/key_presses",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "standard",
    "destination": {
      "discoveryStatus": "visited",
      "reason": null,
      "error": null,
      "httpStatus": 200,
      "finalUrl": "https://the-internet.herokuapp.com/key_presses",
      "title": "The Internet",
      "headings": [
        {
          "level": "h3",
          "text": "Key Presses",
          "isVisible": true
        }
      ]
    }
  },
  {
    "number": 33,
    "name": "Large & Deep DOM",
    "rawHref": "/large",
    "expectedUrl": "https://the-internet.herokuapp.com/large",
    "path": "/large",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "standard",
    "destination": {
      "discoveryStatus": "visited",
      "reason": null,
      "error": null,
      "httpStatus": 200,
      "finalUrl": "https://the-internet.herokuapp.com/large",
      "title": "The Internet",
      "headings": [
        {
          "level": "h3",
          "text": "Large & Deep DOM",
          "isVisible": true
        },
        {
          "level": "h4",
          "text": "No Siblings",
          "isVisible": true
        },
        {
          "level": "h4",
          "text": "Siblings",
          "isVisible": true
        },
        {
          "level": "h4",
          "text": "Table",
          "isVisible": true
        }
      ]
    }
  },
  {
    "number": 34,
    "name": "Multiple Windows",
    "rawHref": "/windows",
    "expectedUrl": "https://the-internet.herokuapp.com/windows",
    "path": "/windows",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "standard",
    "destination": {
      "discoveryStatus": "visited",
      "reason": null,
      "error": null,
      "httpStatus": 200,
      "finalUrl": "https://the-internet.herokuapp.com/windows",
      "title": "The Internet",
      "headings": [
        {
          "level": "h3",
          "text": "Opening a new window",
          "isVisible": true
        }
      ]
    }
  },
  {
    "number": 35,
    "name": "Nested Frames",
    "rawHref": "/nested_frames",
    "expectedUrl": "https://the-internet.herokuapp.com/nested_frames",
    "path": "/nested_frames",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "nested-frames",
    "destination": {
      "discoveryStatus": "visited",
      "reason": null,
      "error": null,
      "httpStatus": 200,
      "finalUrl": "https://the-internet.herokuapp.com/nested_frames",
      "title": "",
      "headings": []
    }
  },
  {
    "number": 36,
    "name": "Notification Messages",
    "rawHref": "/notification_message",
    "expectedUrl": "https://the-internet.herokuapp.com/notification_message",
    "path": "/notification_message",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "standard",
    "destination": {
      "discoveryStatus": "visited",
      "reason": null,
      "error": null,
      "httpStatus": 200,
      "finalUrl": "https://the-internet.herokuapp.com/notification_message_rendered",
      "title": "The Internet",
      "headings": [
        {
          "level": "h3",
          "text": "Notification Message",
          "isVisible": true
        }
      ]
    }
  },
  {
    "number": 37,
    "name": "Redirect Link",
    "rawHref": "/redirector",
    "expectedUrl": "https://the-internet.herokuapp.com/redirector",
    "path": "/redirector",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "standard",
    "destination": {
      "discoveryStatus": "visited",
      "reason": null,
      "error": null,
      "httpStatus": 200,
      "finalUrl": "https://the-internet.herokuapp.com/redirector",
      "title": "The Internet",
      "headings": [
        {
          "level": "h3",
          "text": "Redirection",
          "isVisible": true
        }
      ]
    }
  },
  {
    "number": 38,
    "name": "Secure File Download",
    "rawHref": "/download_secure",
    "expectedUrl": "https://the-internet.herokuapp.com/download_secure",
    "path": "/download_secure",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "secure-download",
    "destination": {
      "discoveryStatus": "skipped",
      "reason": "Requires authentication before downloading.",
      "error": null,
      "httpStatus": null,
      "finalUrl": null,
      "title": null,
      "headings": []
    }
  },
  {
    "number": 39,
    "name": "Shadow DOM",
    "rawHref": "/shadowdom",
    "expectedUrl": "https://the-internet.herokuapp.com/shadowdom",
    "path": "/shadowdom",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "standard",
    "destination": {
      "discoveryStatus": "visited",
      "reason": null,
      "error": null,
      "httpStatus": 200,
      "finalUrl": "https://the-internet.herokuapp.com/shadowdom",
      "title": "The Internet",
      "headings": [
        {
          "level": "h1",
          "text": "Simple template",
          "isVisible": true
        }
      ]
    }
  },
  {
    "number": 40,
    "name": "Shifting Content",
    "rawHref": "/shifting_content",
    "expectedUrl": "https://the-internet.herokuapp.com/shifting_content",
    "path": "/shifting_content",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "standard",
    "destination": {
      "discoveryStatus": "visited",
      "reason": null,
      "error": null,
      "httpStatus": 200,
      "finalUrl": "https://the-internet.herokuapp.com/shifting_content",
      "title": "The Internet",
      "headings": [
        {
          "level": "h3",
          "text": "Shifting Content",
          "isVisible": true
        }
      ]
    }
  },
  {
    "number": 41,
    "name": "Slow Resources",
    "rawHref": "/slow",
    "expectedUrl": "https://the-internet.herokuapp.com/slow",
    "path": "/slow",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "slow-resource",
    "destination": {
      "discoveryStatus": "skipped",
      "reason": "Intentionally slow response.",
      "error": null,
      "httpStatus": null,
      "finalUrl": null,
      "title": null,
      "headings": []
    }
  },
  {
    "number": 42,
    "name": "Sortable Data Tables",
    "rawHref": "/tables",
    "expectedUrl": "https://the-internet.herokuapp.com/tables",
    "path": "/tables",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "standard",
    "destination": {
      "discoveryStatus": "visited",
      "reason": null,
      "error": null,
      "httpStatus": 200,
      "finalUrl": "https://the-internet.herokuapp.com/tables",
      "title": "The Internet",
      "headings": [
        {
          "level": "h3",
          "text": "Data Tables",
          "isVisible": true
        },
        {
          "level": "h4",
          "text": "Example 1",
          "isVisible": true
        },
        {
          "level": "h4",
          "text": "Example 2",
          "isVisible": true
        }
      ]
    }
  },
  {
    "number": 43,
    "name": "Status Codes",
    "rawHref": "/status_codes",
    "expectedUrl": "https://the-internet.herokuapp.com/status_codes",
    "path": "/status_codes",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "standard",
    "destination": {
      "discoveryStatus": "visited",
      "reason": null,
      "error": null,
      "httpStatus": 200,
      "finalUrl": "https://the-internet.herokuapp.com/status_codes",
      "title": "The Internet",
      "headings": [
        {
          "level": "h3",
          "text": "Status Codes",
          "isVisible": true
        }
      ]
    }
  },
  {
    "number": 44,
    "name": "Typos",
    "rawHref": "/typos",
    "expectedUrl": "https://the-internet.herokuapp.com/typos",
    "path": "/typos",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "standard",
    "destination": {
      "discoveryStatus": "visited",
      "reason": null,
      "error": null,
      "httpStatus": 200,
      "finalUrl": "https://the-internet.herokuapp.com/typos",
      "title": "The Internet",
      "headings": [
        {
          "level": "h3",
          "text": "Typos",
          "isVisible": true
        }
      ]
    }
  },
  {
    "number": 45,
    "name": "WYSIWYG Editor",
    "rawHref": "/tinymce",
    "expectedUrl": "https://the-internet.herokuapp.com/tinymce",
    "path": "/tinymce",
    "isInternal": true,
    "isVisible": true,
    "opensNewTab": false,
    "testType": "standard",
    "destination": {
      "discoveryStatus": "visited",
      "reason": null,
      "error": null,
      "httpStatus": 200,
      "finalUrl": "https://the-internet.herokuapp.com/tinymce",
      "title": "The Internet",
      "headings": [
        {
          "level": "h3",
          "text": "An iFrame containing the TinyMCE WYSIWYG Editor",
          "isVisible": true
        }
      ]
    }
  },
  {
    "number": 46,
    "name": "Elemental Selenium",
    "rawHref": "http://elementalselenium.com/",
    "expectedUrl": "http://elementalselenium.com/",
    "path": "/",
    "isInternal": false,
    "isVisible": true,
    "opensNewTab": true,
    "testType": "external",
    "destination": {
      "discoveryStatus": "skipped",
      "reason": "External destinations are not visited.",
      "error": null,
      "httpStatus": null,
      "finalUrl": null,
      "title": null,
      "headings": []
    }
  }
] as const;

export type HomepageNavigationLink = (typeof homepageNavigation)[number];
