// Generated by scripts/discover-links.mjs.
// Review changes before committing them as test expectations.

export const internalLinks = [
  {
    "category": "Internal content",
    "names": [
      "LOGO"
    ],
    "href": "https://www.southernknightscruisers.com/index.html",
    "sourcePages": [
      "https://www.southernknightscruisers.com/index.html",
      "https://www.southernknightscruisers.com/about.html",
      "https://www.southernknightscruisers.com/events.html",
      "https://www.southernknightscruisers.com/gallery.html",
      "https://www.southernknightscruisers.com/news.html",
      "https://www.southernknightscruisers.com/sponsors.html",
      "https://www.southernknightscruisers.com/veterans-show.html",
      "https://www.southernknightscruisers.com/register_content.html",
      "https://www.southernknightscruisers.com/vendor-register_content.html",
      "https://www.southernknightscruisers.com/food-vendor-register_content.html",
      "https://www.southernknightscruisers.com/vet-organizations.html",
      "https://www.southernknightscruisers.com/contact.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "Internal content",
    "names": [
      "Click Here!",
      "Events"
    ],
    "href": "https://www.southernknightscruisers.com/events.html",
    "sourcePages": [
      "https://www.southernknightscruisers.com/index.html",
      "https://www.southernknightscruisers.com/about.html",
      "https://www.southernknightscruisers.com/gallery.html",
      "https://www.southernknightscruisers.com/news.html",
      "https://www.southernknightscruisers.com/sponsors.html",
      "https://www.southernknightscruisers.com/register_content.html",
      "https://www.southernknightscruisers.com/vendor-register_content.html",
      "https://www.southernknightscruisers.com/food-vendor-register_content.html",
      "https://www.southernknightscruisers.com/vet-organizations.html",
      "https://www.southernknightscruisers.com/contact.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "Internal content",
    "names": [
      "About"
    ],
    "href": "https://www.southernknightscruisers.com/about.html",
    "sourcePages": [
      "https://www.southernknightscruisers.com/index.html",
      "https://www.southernknightscruisers.com/about.html",
      "https://www.southernknightscruisers.com/events.html",
      "https://www.southernknightscruisers.com/news.html",
      "https://www.southernknightscruisers.com/sponsors.html",
      "https://www.southernknightscruisers.com/register_content.html",
      "https://www.southernknightscruisers.com/vendor-register_content.html",
      "https://www.southernknightscruisers.com/food-vendor-register_content.html",
      "https://www.southernknightscruisers.com/vet-organizations.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "Internal content",
    "names": [
      "Gallery"
    ],
    "href": "https://www.southernknightscruisers.com/gallery.html",
    "sourcePages": [
      "https://www.southernknightscruisers.com/index.html",
      "https://www.southernknightscruisers.com/about.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "Internal content",
    "names": [
      "Sponsors"
    ],
    "href": "https://www.southernknightscruisers.com/sponsors.html",
    "sourcePages": [
      "https://www.southernknightscruisers.com/index.html",
      "https://www.southernknightscruisers.com/about.html",
      "https://www.southernknightscruisers.com/events.html",
      "https://www.southernknightscruisers.com/gallery.html",
      "https://www.southernknightscruisers.com/news.html",
      "https://www.southernknightscruisers.com/register_content.html",
      "https://www.southernknightscruisers.com/vendor-register_content.html",
      "https://www.southernknightscruisers.com/food-vendor-register_content.html",
      "https://www.southernknightscruisers.com/vet-organizations.html",
      "https://www.southernknightscruisers.com/contact.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "Internal content",
    "names": [
      "Contact"
    ],
    "href": "https://www.southernknightscruisers.com/contact.html",
    "sourcePages": [
      "https://www.southernknightscruisers.com/index.html",
      "https://www.southernknightscruisers.com/about.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "Internal content",
    "names": [
      "Car Show",
      "Veterans Car Show",
      "Click Here!"
    ],
    "href": "https://www.southernknightscruisers.com/veterans-show.html",
    "sourcePages": [
      "https://www.southernknightscruisers.com/index.html",
      "https://www.southernknightscruisers.com/about.html",
      "https://www.southernknightscruisers.com/events.html",
      "https://www.southernknightscruisers.com/gallery.html",
      "https://www.southernknightscruisers.com/news.html",
      "https://www.southernknightscruisers.com/sponsors.html",
      "https://www.southernknightscruisers.com/register_content.html",
      "https://www.southernknightscruisers.com/vendor-register_content.html",
      "https://www.southernknightscruisers.com/food-vendor-register_content.html",
      "https://www.southernknightscruisers.com/vet-organizations.html",
      "https://www.southernknightscruisers.com/contact.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "Internal content",
    "names": [
      "News"
    ],
    "href": "https://www.southernknightscruisers.com/news.html",
    "sourcePages": [
      "https://www.southernknightscruisers.com/index.html",
      "https://www.southernknightscruisers.com/about.html",
      "https://www.southernknightscruisers.com/events.html",
      "https://www.southernknightscruisers.com/gallery.html",
      "https://www.southernknightscruisers.com/sponsors.html",
      "https://www.southernknightscruisers.com/contact.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "Internal content",
    "names": [
      "Veteran's Organizations",
      "About Our Veteran’s Organizations",
      "About Our Veteran's Organizations"
    ],
    "href": "https://www.southernknightscruisers.com/vet-organizations.html",
    "sourcePages": [
      "https://www.southernknightscruisers.com/index.html",
      "https://www.southernknightscruisers.com/about.html",
      "https://www.southernknightscruisers.com/events.html",
      "https://www.southernknightscruisers.com/gallery.html",
      "https://www.southernknightscruisers.com/news.html",
      "https://www.southernknightscruisers.com/sponsors.html",
      "https://www.southernknightscruisers.com/veterans-show.html",
      "https://www.southernknightscruisers.com/contact.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "Internal content",
    "names": [
      "pictures from 2023 Veterans Car Show"
    ],
    "href": "https://www.southernknightscruisers.com/2023_Veterans.html",
    "sourcePages": [
      "https://www.southernknightscruisers.com/gallery.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "Internal content",
    "names": [
      "2024 Hardees Cruise Ins Pictures"
    ],
    "href": "https://www.southernknightscruisers.com/2024_Hardees_Cruise_Ins.html",
    "sourcePages": [
      "https://www.southernknightscruisers.com/gallery.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "Internal content",
    "names": [
      "2024 Richlands Creamery Cruise Ins Pictures"
    ],
    "href": "https://www.southernknightscruisers.com/2024_Richlands_Creamery_Cruise_In.html",
    "sourcePages": [
      "https://www.southernknightscruisers.com/gallery.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "Internal content",
    "names": [
      "2023 America Legion Car and Bike Show"
    ],
    "href": "https://www.southernknightscruisers.com/2023_America_Legion_Car_and_Bike_Show.html",
    "sourcePages": [
      "https://www.southernknightscruisers.com/gallery.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "Internal content",
    "names": [
      "Veterans Car & Bike Show Details",
      "(unnamed link)",
      "Car Show Details"
    ],
    "href": "https://www.southernknightscruisers.com/veterans-show.html#show_details",
    "sourcePages": [
      "https://www.southernknightscruisers.com/veterans-show.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "Internal content",
    "names": [
      "Veterans Car & Bike Show Registration",
      "(unnamed link)",
      "Car Show Registration"
    ],
    "href": "https://www.southernknightscruisers.com/veterans-show.html#show_registration",
    "sourcePages": [
      "https://www.southernknightscruisers.com/veterans-show.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "Internal content",
    "names": [
      "(unnamed link)",
      "Vendor Registration"
    ],
    "href": "https://www.southernknightscruisers.com/veterans-show.html#vendor_registration",
    "sourcePages": [
      "https://www.southernknightscruisers.com/veterans-show.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "Internal content",
    "names": [
      "(unnamed link)",
      "Car Show Contacts"
    ],
    "href": "https://www.southernknightscruisers.com/veterans-show.html#show_contacts",
    "sourcePages": [
      "https://www.southernknightscruisers.com/veterans-show.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "Internal content",
    "names": [
      "2026 Online Show Registration"
    ],
    "href": "https://www.southernknightscruisers.com/register_content.html",
    "sourcePages": [
      "https://www.southernknightscruisers.com/veterans-show.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "Internal content",
    "names": [
      "2026 Online Vendor Registration"
    ],
    "href": "https://www.southernknightscruisers.com/vendor-register_content.html",
    "sourcePages": [
      "https://www.southernknightscruisers.com/veterans-show.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "Internal content",
    "names": [
      "2026 Online Food Vendor Registration"
    ],
    "href": "https://www.southernknightscruisers.com/food-vendor-register_content.html",
    "sourcePages": [
      "https://www.southernknightscruisers.com/veterans-show.html"
    ],
    "elementTypes": [
      "link"
    ]
  }
] as const;

export type InternalLink =
  (typeof internalLinks)[number];
