// Generated by scripts/discover-links.mjs.
// Review changes before committing them as test expectations.

export const startUrl = "https://www.southernknightscruisers.com/index.html";

export const navigationRoutes = [
  {
    "id": "home",
    "linkName": "Home",
    "href": "index.html",
    "expectedUrl": "https://www.southernknightscruisers.com/index.html",
    "expectedHeading": "Hardees Cruise-Ins"
  },
  {
    "id": "about",
    "linkName": "About",
    "href": "about.html",
    "expectedUrl": "https://www.southernknightscruisers.com/about.html",
    "expectedHeading": "About Southern Knights Cruisers"
  },
  {
    "id": "events",
    "linkName": "Events",
    "href": "events.html",
    "expectedUrl": "https://www.southernknightscruisers.com/events.html",
    "expectedHeading": "Southern Knights Cruisers Events"
  },
  {
    "id": "gallery",
    "linkName": "Gallery",
    "href": "gallery.html",
    "expectedUrl": "https://www.southernknightscruisers.com/gallery.html",
    "expectedHeading": "Southern Knights Cruisers Gallery"
  },
  {
    "id": "news",
    "linkName": "News",
    "href": "news.html",
    "expectedUrl": "https://www.southernknightscruisers.com/news.html",
    "expectedHeading": "Southern Knights Cruisers News"
  },
  {
    "id": "sponsors",
    "linkName": "Sponsors",
    "href": "sponsors.html",
    "expectedUrl": "https://www.southernknightscruisers.com/sponsors.html",
    "expectedHeading": "Southern Knights Cruisers Sponsors"
  },
  {
    "id": "car-show",
    "linkName": "Car Show",
    "href": "veterans-show.html",
    "expectedUrl": "https://www.southernknightscruisers.com/veterans-show.html",
    "expectedHeading": "Southern Knights Cruisers Veterans Car Show"
  },
  {
    "id": "contact",
    "linkName": "Contact",
    "href": "contact.html",
    "expectedUrl": "https://www.southernknightscruisers.com/contact.html",
    "expectedHeading": "Contact Southern Knights Cruisers"
  }
] as const;

export type NavigationRoute =
  (typeof navigationRoutes)[number];
