// Generated by scripts/discover-links.mjs.
// Review changes before committing them as test expectations.

export const specialLinks = [
  {
    "category": "Email",
    "names": [
      "uworime@comcast.net"
    ],
    "href": "mailto:uworime@comcast.net",
    "sourcePages": [
      "https://www.southernknightscruisers.com/index.html",
      "https://www.southernknightscruisers.com/events.html",
      "https://www.southernknightscruisers.com/veterans-show.html",
      "https://www.southernknightscruisers.com/contact.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "Placeholder/broken",
    "names": [
      "JW Electric"
    ],
    "href": "https://www.southernknightscruisers.com/index.html#",
    "sourcePages": [
      "https://www.southernknightscruisers.com/index.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "Placeholder/broken",
    "names": [
      "JW Electric"
    ],
    "href": "https://www.southernknightscruisers.com/about.html#",
    "sourcePages": [
      "https://www.southernknightscruisers.com/about.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "Placeholder/broken",
    "names": [
      "JW Electric"
    ],
    "href": "https://www.southernknightscruisers.com/events.html#",
    "sourcePages": [
      "https://www.southernknightscruisers.com/events.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "Placeholder/broken",
    "names": [
      "JW Electric"
    ],
    "href": "https://www.southernknightscruisers.com/gallery.html#",
    "sourcePages": [
      "https://www.southernknightscruisers.com/gallery.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "Placeholder/broken",
    "names": [
      "JW Electric"
    ],
    "href": "https://www.southernknightscruisers.com/news.html#",
    "sourcePages": [
      "https://www.southernknightscruisers.com/news.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "Placeholder/broken",
    "names": [
      "JW Electric"
    ],
    "href": "https://www.southernknightscruisers.com/sponsors.html#",
    "sourcePages": [
      "https://www.southernknightscruisers.com/sponsors.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "PDF",
    "names": [
      "2026 Show Registration Form"
    ],
    "href": "https://www.southernknightscruisers.com/docs/Show%20Registration%20Form-2026.pdf",
    "sourcePages": [
      "https://www.southernknightscruisers.com/veterans-show.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "Payment",
    "names": [
      "https://www.paypal.com/paypalme/SkCruisers/25"
    ],
    "href": "https://www.paypal.com/paypalme/SkCruisers/25",
    "sourcePages": [
      "https://www.southernknightscruisers.com/veterans-show.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "PDF",
    "names": [
      "2026 Vendor Registration Form"
    ],
    "href": "https://www.southernknightscruisers.com/docs/Vendor%20registration%20form-2026.pdf",
    "sourcePages": [
      "https://www.southernknightscruisers.com/veterans-show.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "Payment",
    "names": [
      "https://www.paypal.com/paypalme/SkCruisers/"
    ],
    "href": "https://www.paypal.com/paypalme/SkCruisers/",
    "sourcePages": [
      "https://www.southernknightscruisers.com/veterans-show.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "PDF",
    "names": [
      "2026 Food Vendor Registration Form"
    ],
    "href": "https://www.southernknightscruisers.com/docs/Food%20Vendor%20registration%20form-2026.pdf",
    "sourcePages": [
      "https://www.southernknightscruisers.com/veterans-show.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "Placeholder/broken",
    "names": [
      "JW Electric"
    ],
    "href": "https://www.southernknightscruisers.com/veterans-show.html#",
    "sourcePages": [
      "https://www.southernknightscruisers.com/veterans-show.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "Placeholder/broken",
    "names": [
      "JW Electric"
    ],
    "href": "https://www.southernknightscruisers.com/register_content.html#",
    "sourcePages": [
      "https://www.southernknightscruisers.com/register_content.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "Placeholder/broken",
    "names": [
      "JW Electric"
    ],
    "href": "https://www.southernknightscruisers.com/vendor-register_content.html#",
    "sourcePages": [
      "https://www.southernknightscruisers.com/vendor-register_content.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "Placeholder/broken",
    "names": [
      "JW Electric"
    ],
    "href": "https://www.southernknightscruisers.com/food-vendor-register_content.html#",
    "sourcePages": [
      "https://www.southernknightscruisers.com/food-vendor-register_content.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "Placeholder/broken",
    "names": [
      "JW Electric"
    ],
    "href": "https://www.southernknightscruisers.com/vet-organizations.html#",
    "sourcePages": [
      "https://www.southernknightscruisers.com/vet-organizations.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "Email",
    "names": [
      "tiregirl402@yahoo.com"
    ],
    "href": "mailto:tiregirl402@yahoo.com",
    "sourcePages": [
      "https://www.southernknightscruisers.com/contact.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "Placeholder/broken",
    "names": [
      "JW Electric"
    ],
    "href": "https://www.southernknightscruisers.com/contact.html#",
    "sourcePages": [
      "https://www.southernknightscruisers.com/contact.html"
    ],
    "elementTypes": [
      "link"
    ]
  },
  {
    "category": "Payment",
    "names": [
      "Support with PayPal button"
    ],
    "href": "https://www.paypal.com/cgi-bin/webscr",
    "sourcePages": [
      "https://www.southernknightscruisers.com/index.html",
      "https://www.southernknightscruisers.com/about.html",
      "https://www.southernknightscruisers.com/events.html",
      "https://www.southernknightscruisers.com/gallery.html",
      "https://www.southernknightscruisers.com/news.html",
      "https://www.southernknightscruisers.com/sponsors.html",
      "https://www.southernknightscruisers.com/veterans-show.html",
      "https://www.southernknightscruisers.com/register_content.html",
      "https://www.southernknightscruisers.com/vendor-register_content.html",
      "https://www.southernknightscruisers.com/food-vendor-register_content.html",
      "https://www.southernknightscruisers.com/vet-organizations.html",
      "https://www.southernknightscruisers.com/contact.html"
    ],
    "elementTypes": [
      "form"
    ],
    "methods": [
      "POST"
    ]
  }
] as const;

export type SpecialLink =
  (typeof specialLinks)[number];
